#!/usr/bin/env python3
"""Build appendix LaTeX tables from matched Gaussian analysis JSON."""

# Long LaTeX rows are clearer as single source strings.
# ruff: noqa: E501

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

MODEL_NAMES = {
    "audio_flamingo": "Audio Flamingo NeXT",
    "naturelm": "NatureLM-audio v1.0",
    "qwen": "Qwen3-Omni",
}
TIER4 = {
    "beans_next_crow_4way",
    "beans_next_crow_description",
    "beans_next_dcase_fewshot_detection_balanced",
    "beans_next_gibbon_fewshot_detection_balanced",
    "beans_next_giant_otter_4way",
    "beans_next_unseen_species_4way",
    "beans_next_zebra_4way",
    "beans_next_zebra_description",
}
PRIMARY_METRICS = (
    "coverage_aware_freq_mean_iou",
    "accuracy",
    "absolute_error",
    "count_mae",
    "cider",
    "species_f1",
)
CLASSIFICATION_METRICS = ("top1_accuracy", "accuracy", "macro_f1", "species_f1")


def task_tier(task_id: str) -> int:
    """Return the BEANS-Next tier for a task ID.

    Returns
    -------
    int
        Tier number from one through four.
    """

    if task_id in TIER4:
        return 4
    if task_id.startswith("beans_next_t3_"):
        return 3
    if task_id.startswith(("beans_next_t1_", "beans_next_f0_")):
        return 1
    return 2


def _display_task(task_id: str) -> str:
    return task_id.removeprefix("beans_next_").replace("_", " ")


def _primary(task_id: str, row: dict[str, Any]) -> tuple[str, str, float, int]:
    metrics = row["metrics"]
    key = next(name for name in PRIMARY_METRICS if name in metrics)
    scale = (
        100 if key in {"accuracy", "species_f1", "coverage_aware_freq_mean_iou"} else 1
    )
    unit = "Hz" if "f0_mean" in task_id else ("dB" if "snr" in task_id else "count")
    labels = {
        "accuracy": r"Acc. (\%)",
        "absolute_error": f"MAE ({unit})",
        "count_mae": "Count MAE",
        "cider": "CIDEr",
        "species_f1": r"Species F1 (\%)",
        "coverage_aware_freq_mean_iou": r"IoU (\%)",
    }
    precision = 5 if key == "cider" else 2
    return key, labels[key], scale, precision


def _task_tables(data: dict[str, Any]) -> list[str]:
    lines = ["% Generated by scripts/build_gaussian_appendix_tables.py."]
    for model, report in data.items():
        lines += [
            r"\begingroup\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{p{6.3cm}lrrrr}",
            rf"\caption{{{MODEL_NAMES[model]}: matched real-audio and Gaussian-noise results. Accuracy and species F1 use percentages. CIDEr uses its raw scale. $\Delta$ is Audio$-$Noise.}}\label{{tab:gaussian-{model.replace('_', '-')}}}\\",
            r"\toprule Task & Metric & $n$ & Audio & Noise & $\Delta$ \\ \midrule\endfirsthead",
            r"\toprule Task & Metric & $n$ & Audio & Noise & $\Delta$ \\ \midrule\endhead",
            r"\bottomrule\endfoot",
        ]
        for task_id, row in report["tasks"].items():
            key, label, scale, precision = _primary(task_id, row)
            values = [
                row["metrics"][key][arm] * scale
                for arm in ("real", "noise", "audio_minus_noise")
            ]
            formatted = " & ".join(f"{value:.{precision}f}" for value in values)
            lines.append(
                f"{_display_task(task_id)} & {label} & {row['n_samples']} & {formatted} \\\\"
            )
        lines += [r"\end{longtable}", r"\endgroup", ""]
    return lines


def _diagnostic_tables(data: dict[str, Any]) -> list[str]:
    lines = [
        r"\begingroup\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{longtable}{llrrrrr}",
        r"\caption{Numeric parsing diagnostics. The MAE values use only parsed predictions.}\label{tab:gaussian-parse}\\",
        r"\toprule Model & Task & $n$ & Audio parsed & Noise parsed & Audio fail (\%) & Noise fail (\%) \\ \midrule\endfirsthead",
        r"\toprule Model & Task & $n$ & Audio parsed & Noise parsed & Audio fail (\%) & Noise fail (\%) \\ \midrule\endhead",
        r"\bottomrule\endfoot",
    ]
    for model, report in data.items():
        for task_id, row in report["tasks"].items():
            audio = row["real_diagnostics"]
            noise = row["noise_diagnostics"]
            denominator = audio["numeric_parse_denominator"]
            if not denominator:
                continue
            if denominator != noise["numeric_parse_denominator"]:
                raise ValueError(f"numeric parse denominators differ for {task_id}")
            audio_parsed = denominator - audio["numeric_parse_failure_count"]
            noise_parsed = denominator - noise["numeric_parse_failure_count"]
            lines.append(
                f"{MODEL_NAMES[model]} & {_display_task(task_id)} & {row['n_samples']} & "
                f"{audio_parsed} & {noise_parsed} & {100 * audio['numeric_parse_failure_rate']:.1f} & "
                f"{100 * noise['numeric_parse_failure_rate']:.1f} \\\\"
            )
    lines += [r"\end{longtable}", r"\endgroup", ""]
    return lines


def _tier_tables(data: dict[str, Any]) -> list[str]:
    lines = [
        r"\begin{table}[ht]",
        r"\centering\scriptsize",
        r"\caption{Tier summaries. Classification is the unweighted mean across classification tasks. Refusal values are fixed-phrase heuristic candidate rates over non-error predictions.}\label{tab:gaussian-tier-summary}",
        r"\begin{tabular}{llrrrr}",
        r"\toprule Model & Tier & Audio class. (\%) & Noise class. (\%) & Audio refusal (\%) & Noise refusal (\%) \\ \midrule",
    ]
    for model, report in data.items():
        for tier in range(1, 5):
            rows = [
                row for task, row in report["tasks"].items() if task_tier(task) == tier
            ]
            pairs = []
            for row in rows:
                metric = next(
                    (name for name in CLASSIFICATION_METRICS if name in row["metrics"]),
                    None,
                )
                if metric:
                    pairs.append(row["metrics"][metric])
            real_class = 100 * sum(pair["real"] for pair in pairs) / len(pairs)
            noise_class = 100 * sum(pair["noise"] for pair in pairs) / len(pairs)
            real_n = sum(
                row["real_diagnostics"]["non_error_denominator"] for row in rows
            )
            noise_n = sum(
                row["noise_diagnostics"]["non_error_denominator"] for row in rows
            )
            real_ref = sum(
                row["real_diagnostics"]["refusal_heuristic_count"] for row in rows
            )
            noise_ref = sum(
                row["noise_diagnostics"]["refusal_heuristic_count"] for row in rows
            )
            lines.append(
                f"{MODEL_NAMES[model]} & {tier} & {real_class:.2f} & {noise_class:.2f} & "
                f"{100 * real_ref / real_n:.3f} & {100 * noise_ref / noise_n:.3f} \\\\"
            )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return lines


def build_tables(data: dict[str, Any]) -> str:
    """Return all Gaussian appendix tables as LaTeX.

    Returns
    -------
    str
        Generated LaTeX source.

    Raises
    ------
    ValueError
        If the analysis contains an unknown model.
    """

    unknown = set(data) - set(MODEL_NAMES)
    if unknown:
        raise ValueError(f"unknown models: {sorted(unknown)}")
    return (
        "\n".join(_tier_tables(data) + _task_tables(data) + _diagnostic_tables(data))
        + "\n"
    )


def main() -> int:
    """Read matched analysis JSON and write deterministic LaTeX tables.

    Returns
    -------
    int
        Zero after the output is written.
    """

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("analysis", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    data = json.loads(args.analysis.read_text(encoding="utf-8"))
    args.output.write_text(build_tables(data), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
